# Generated by Django 4.1.7 on 2023-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_url_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='custom_url',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
